spring.application.name=redCake

# Disable the default web application type because this is a non-web application
# If you use Spring Boot's embedded Tomcat, it normally starts an HTTP server on port 8080.
# Now Spring Boot won't start Tomcat.
spring.main.web-application-type=none
